### ISSUE TITLE
starting this repo right

### ISSUE THREAD

**Issue by BurningTreeC** [TiddlyWiki/aTW#1]
This repository is going to contain the code for an Android app that runs tiddlywiki files as web-applications

we need to figure some things out

- [x] copy the license from the TiddlyWiki repo over and change things if necessary

- [x] think about the structure of the repo / how to improve the structure (my) Android Studio creates / or just use that

- [x] create a basic skeleton for the app

- [ ] create a readme with build instructions and info/instructions about contributing

**Comment by Jermolene** [comment]
Hi @BurningTreeC that sounds great.

Thinking about the repo structure, one thing to consider is whether you want to produce the documentation with TiddlyWiki (@cjhunt uses a TW as the docs for Quine quite nicely: on installation the docs wiki is dropped into the Quine folder on the device). If so, you could also generate the readme.md file from the wiki, as we do for the TW5 repo.

Bear in mind that in open source everything we do is provisional, and subject to later improvement. None of this needs to be perfect immediately, and making it perfect isn't even your prime responsibility. The trick is to lay down enough of a clear story showing your intentions so that other people can follow what is going on and join in.

Meanwhile, there's the fun question of what icon you're going to use? :smile:

**Comment by BurningTreeC** [comment]
Hi @Jermolene ,

>Meanwhile, there's the fun question of what icon you're going to use? 😄

The core icon ($:/core/icon) looks great as app icon but I'm not settled. I'd use that one except there are or evolve better ideas or I'm not allowed to do so

>Bear in mind that in open source everything we do is provisional, and subject to later improvement. None of this needs to be perfect immediately, and making it perfect isn't even your prime responsibility. The trick is to lay down enough of a clear story showing your intentions so that other people can follow what is going on and join in.

Thank you, I'm trying to do so by adding some basic issues and showing where help is needed
I use it as a starting-brainstorm before adding the code

I'll have a look at how @cjhunt does it tomorrow, thanks for the hint(s) and help!

**Comment by BurningTreeC** [comment]
@Jermolene apologies, I don't understand what you meant with the documentation and the readme build

with documentation do you mean a separate wiki that contains info/help regarding the application and that could be shipped with the app and accessible from within it?

what readme could then be built with that wiki, the one of this repo, if I understand it right?

I don't see the relationships between one and the other, would you mind to explain what you intended?

**Comment by Wattaged** [comment]
It looks to me like if you go to @cjhunt , then 'codingForTiddlyWiki5' and then 'View code' there is a bash script 'bldCodingForTiddlyWiki5.sh' which takes the contents of his 'editions/codingForTIddlyWiki5'  and generates a TW from it, which is then located on github.io as the project home page and also updates the readme.md for the project. How you run a bash script on github is beyond me.
So, if all the tids for aTW go in one directory the bash script would generate a working aTw wiki as homepage, with a readme.md I'm the right place. If you also add documentation tiddlers to the code directory (tagged documentation?) they'll be included in the generated wiki too.
That's how I think it works!

**Comment by BurningTreeC** [comment]
Thank you for investigating this @Wattaged , I didn't find time to look into it. I'll have a look when I'm ready, now I don't have to do research anymore :smile:

**Comment by Wattaged** [comment]
Hope I'm right. Might be able to get that gantt chart plugin to work on it ;)

**Comment by YakovL** [comment]
Hi, I guess, there is some initial discussion thread at google groups, could reference it if that's the case?

Are you going to support only TiddlyWiki5 with this app or TiddlyWiki Classic too?
