### ISSUE TITLE
app icon

### ISSUE THREAD

**Issue by BurningTreeC** [TiddlyWiki/aTW#4]
what should the app icon be

in my tests I'm using the core tiddlywiki icon which looks very good
on dark backgrounds it's hard to see because it's black

for now I make it the tiddlywiki standard foreground color `#333333`

**Comment by Jermolene** [comment]
Hi @BurningTreeC perhaps post a snapshot of the home screen here?

For comparison, TiddlyDesktop uses this icon:

![app-icon128](https://user-images.githubusercontent.com/174761/50893602-27618e00-13f9-11e9-968e-e5af866e00b6.png)

Quine uses this icon:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/174761/50893687-5a0b8680-13f9-11e9-980c-b6a88b45935d.png">

**Comment by BurningTreeC** [comment]
Hi @Wattaged , @Jermolene 

I'm using an svg icon because Android Studio conveniently converts it so that it'll look good on different screen sizes

The icon gets rendered differently depending on the device-settings, with a round/rectangular background or without background. Sometimes Android renders its own additional icon-backgrounds, sometimes not. I don't know yet how to control that. On my device it's without background and the cat renders a beautiful shadow, I like that

See the [ic_launcher.xml](https://github.com/TiddlyWiki/aTW/blob/master/mobile/src/main/res/drawable/ic_launcher.xml) file for more details

For more control over app-icon styling we'll need to dig deeper into the different options

This is how it looks in the Android Emulator on my desktop:
![screenshot_1547033400](https://user-images.githubusercontent.com/9407182/50897191-ab247600-140b-11e9-98e8-502057b86f36.png)

This is how it looks on my phone, a Huawei honor 9 lite, Android 8.0:
![screenshot_20190109-124136](https://user-images.githubusercontent.com/9407182/50897445-651be200-140c-11e9-8cae-d8413c5c13bf.jpg)

**Comment by Wattaged** [comment]
Both look good to me, but like you say the cat won't show on android if you have a black homescreen. I've heard mention of 'material theme' on google stuff. Is it possible to go for the simplest option, white cat, black surround or vice versa, and sacrifice the shadow (which might not match other app icons or themes anyway.) or White surround, black cat with shadow from cat?
Sorry if this is less than helpful - still getting my head round github.

**Comment by BurningTreeC** [comment]
@Wattaged 
thank you, no this is very helpful, don't hesitate to jump in to discussions, I'm very grateful about that

the icon can still be changed and we'll find a suitable solution

**Comment by TiddlyTweeter** [comment]
As an art person I like the Quine because it FILLS SPACE. If you look at my cat to left you will see its tail arrangement better fills space than the default cat

**Comment by BurningTreeC** [comment]
thanks @TiddlyTweeter , I personally think the quine icon is too asymmetrical and distracting, it makes me think what it wants to tell me, but the icon is just a launcher

I don't like the quine icon at all is what I'm saying :smile:

**Comment by TiddlyTweeter** [comment]
Right. Stay cat. Just tame the tail which breaks circles. :-)

**Comment by Jermolene** [comment]
For the record, there are a bunch of other pictures of Jack [on Flickr](
https://www.flickr.com/photos/jermy/albums/72157649476626450).

**Comment by BurningTreeC** [comment]
I think I at the moment I want to keep this an open decision up to the point someone comes with a good design (already designed) or a pull request that does the work

**Comment by BurningTreeC** [comment]
A cat without tail is just a ca ;)
